### ISSUE TITLE
bug RCON不应该在命令前带"/"

### ISSUE THREAD

**Issue by Wind-Rise** [Apricityx/Koishi-plugin-Minecraft-RCON#2]
![image](https://github.com/Apricityx/Koishi-plugin-Minecraft-RCON/assets/119858176/8806addf-da21-41a8-8ec8-ea97acf65fcb)
我在修改json脚本后，将/whitelist替换为whitelist后仍报错，报错内容如上
在删除了python cache后仍有该问题
首先有debug真的很棒了
但是这种问题还是解决一下
如果没时间我帮你改好代码然后提交以下？/汪汪

**Comment by Apricityx** [comment]
首先感谢你的肯定，根据你的调试信息，看起来是指令出错而不是RCON出错，玩家名是否含有中文或其他特殊符号？

**Comment by Apricityx** [comment]
如果还有任何问题欢迎随时reopen issue

**Comment by Wind-Rise** [comment]
摸了一下，换了别的白名单插件，目前可用，膜拜
对于这个问题确实是/导致的 RCON无法识别带/的指令，我修改了一下就可以正常操作了

**Comment by Apricityx** [comment]
> 摸了一下，换了别的白名单插件，目前可用，膜拜 对于这个问题确实是/导致的 RCON无法识别带/的指令，我修改了一下就可以正常操作了

重构的插件Apricityx/Koishi-plugin-Minecraft-RCON-remake已解决此问题，之前没有做1.20之前的适配，感谢反馈

**Comment by Wind-Rise** [comment]
感谢修复，🌹
